[platformio]
default_envs = esp32c3
src_dir = .

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<.git/> -<.pio/> -<sms_receiver.py>
build_unflags = -std=gnu++11
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -std=gnu++17
lib_deps =
  https://github.com/mgaman/PDUlib.git
  https://github.com/mobizt/ReadyMail.git
